version: '3.9'

services:
  bilder:
    image: ghcr.io/samoht89/bilder:latest
    restart: unless-stopped

  image-carousel:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /mnt/bygg:/mnt/bygg:ro
    restart: unless-stopped
